/**
 * Legacy combined Amazon rule pack (Listing 7 + standard A+ A+S*).
 *
 * Current Amazon sessions use `amazon-marketplaces.ts` and `amazon-catalog.ts`.
 * This pack remains only as a compatibility fallback for pre-session combined plans.
 */
import { definePlatformRulePack, type PlatformSlotRule } from "./types";

const listingSquare = { width: 2000, height: 2000, unit: "px" } as const;
const aPlusHeader = { width: 970, height: 300, unit: "px" } as const;
const aPlusWide = { width: 970, height: 600, unit: "px" } as const;
const aPlusTile = { width: 220, height: 220, unit: "px" } as const;

/** @deprecated New Amazon sessions must use `resolveAmazonPlanningSession()`. */
const slots: PlatformSlotRule[] = [
  {
    key: "MAIN",
    label: "Main image",
    group: "listing",
    order: 1,
    required: true,
    dimensions: listingSquare,
    purpose: "准确展示一个完整、可识别的在售商品主体。",
    planningHints: [
      "使用纯白背景",
      "仅展示一个在售商品",
      "主体完整且占据主要画面",
      "选择能准确识别商品的单一视角",
    ],
    complianceReminders: [
      "不得出现文案、徽章、价格、评分、水印、边框或类似 Amazon 的标记",
      "不得添加未随商品销售的道具或配件",
    ],
  },
  {
    key: "PT01",
    label: "Core benefit",
    group: "listing",
    order: 2,
    required: true,
    dimensions: listingSquare,
    purpose: "用清晰的信息图说明最重要的产品利益点。",
    planningHints: ["只突出一个核心利益点", "使用短标题和可验证证据", "保持商品为主要视觉对象"],
    complianceReminders: ["不得包含价格、促销、评分或无法证明的效果承诺"],
  },
  {
    key: "PT02",
    label: "Feature proof",
    group: "listing",
    order: 3,
    required: true,
    dimensions: listingSquare,
    purpose: "解释关键结构、功能或材质如何产生用户收益。",
    planningHints: ["用局部细节支撑功能", "将功能与用户收益配对", "标注必须来自商品事实"],
    complianceReminders: ["材质、性能、专利和认证声明需有依据"],
  },
  {
    key: "PT03",
    label: "Lifestyle",
    group: "listing",
    order: 4,
    required: true,
    dimensions: listingSquare,
    purpose: "展示目标用户在真实环境中的典型使用场景。",
    planningHints: ["场景与目标市场匹配", "展示合理使用动作", "商品仍需清楚可见"],
    complianceReminders: ["不得通过场景暗示产品不具备的功能或结果"],
  },
  {
    key: "PT04",
    label: "Size and fit",
    group: "listing",
    order: 5,
    required: true,
    dimensions: listingSquare,
    purpose: "帮助买家理解尺寸、容量、适配关系或使用边界。",
    planningHints: ["标明单位", "使用清楚的尺寸参照", "只展示适用于当前 SKU 的参数"],
    complianceReminders: ["尺寸、数量、型号和兼容性必须人工复核"],
  },
  {
    key: "PT05",
    label: "Detail and material",
    group: "listing",
    order: 6,
    required: true,
    dimensions: listingSquare,
    purpose: "通过细节、材质或工艺证据降低购买疑虑。",
    planningHints: ["使用真实质感的近景", "解释可见差异", "避免过度美化商品表面"],
    complianceReminders: ["不得虚构材质、纹理、结构、产地或工艺"],
  },
  {
    key: "PT06",
    label: "Package and trust",
    group: "listing",
    order: 7,
    required: true,
    dimensions: listingSquare,
    purpose: "说明包装清单、使用准备或有依据的品牌信任信息。",
    planningHints: ["展示当前 SKU 实际包含内容", "用清单降低误解", "仅使用已确认的品牌事实"],
    complianceReminders: ["不得加入未包含的配件、赠品、奖项或保证"],
  },
  {
    key: "A+S01",
    label: "A+ header banner",
    group: "a-plus",
    order: 8,
    required: true,
    dimensions: aPlusHeader,
    purpose: "用横幅建立品牌与商品系列的视觉开场。",
    planningHints: ["使用宽幅构图", "保持品牌与商品关系清楚", "文案简短并避开关键裁切区"],
    complianceReminders: ["不得出现价格、促销、评论、联系方式或攻击性号召"],
  },
  {
    key: "A+S02",
    label: "A+ value story",
    group: "a-plus",
    order: 9,
    required: true,
    dimensions: aPlusWide,
    purpose: "完整解释核心用户问题、产品方案和价值证据。",
    planningHints: ["按问题到方案组织信息", "图文共同表达一个主题", "优先使用产品事实"],
    complianceReminders: ["不得使用无依据效果、保证或竞品贬损声明"],
  },
  {
    key: "A+S03",
    label: "A+ feature system",
    group: "a-plus",
    order: 10,
    required: true,
    dimensions: aPlusWide,
    purpose: "以统一结构讲清多项关键功能及其证据。",
    planningHints: ["限制功能数量", "每项功能对应明确证据", "保持标题层级一致"],
    complianceReminders: ["性能、认证、专利和测试数据必须可追溯"],
  },
  {
    key: "A+S04",
    label: "A+ usage story",
    group: "a-plus",
    order: 11,
    required: true,
    dimensions: aPlusWide,
    purpose: "通过生活方式或使用步骤说明商品如何融入场景。",
    planningHints: ["选择目标用户的真实场景", "展示必要步骤", "保持商品和使用结果可辨认"],
    complianceReminders: ["不得包含竞品比较、评论摘录或夸张前后对比"],
  },
  {
    key: "A+S05",
    label: "A+ benefit tile 1",
    group: "a-plus",
    order: 12,
    required: true,
    dimensions: aPlusTile,
    purpose: "用小尺寸模块强化第一项可验证购买理由。",
    planningHints: ["使用单一主体或图标化细节", "标题保持简短", "减少小图内文字"],
    complianceReminders: ["不得出现价格、促销或无依据最高级表述"],
  },
  {
    key: "A+S06",
    label: "A+ benefit tile 2",
    group: "a-plus",
    order: 13,
    required: true,
    dimensions: aPlusTile,
    purpose: "用小尺寸模块强化第二项可验证购买理由。",
    planningHints: ["与其他模块保持视觉一致", "只讲一个差异点", "让商品细节在小尺寸下可辨"],
    complianceReminders: ["不得包含评论、评分或用户背书暗示"],
  },
  {
    key: "A+S07",
    label: "A+ benefit tile 3",
    group: "a-plus",
    order: 14,
    required: true,
    dimensions: aPlusTile,
    purpose: "用小尺寸模块强化第三项可验证购买理由。",
    planningHints: ["优先选择新的事实证据", "避免重复前序模块", "文字与背景保持清晰对比"],
    complianceReminders: ["不得使用竞品名称、对比贬损或市场领先声明"],
  },
  {
    key: "A+S08",
    label: "A+ benefit tile 4",
    group: "a-plus",
    order: 15,
    required: true,
    dimensions: aPlusTile,
    purpose: "以最后一项可信利益点完成 A+ 模块序列。",
    planningHints: ["选择补充型购买理由", "保持系列收尾一致", "小尺寸下维持主体完整"],
    complianceReminders: ["不得出现联系方式、外部链接或强迫性购买号召"],
  },
];

export const amazonRulePack = definePlatformRulePack({
  platformId: "amazon",
  label: "Amazon",
  locale: "en-US",
  promptLanguage: "en",
  slots,
  planningInstructions: [
    "MAIN 只负责准确展示商品；其余 Listing 图按利益点、证据、场景、规格和包装形成互补序列。",
    "A+ 内容延续 Listing 事实，但使用品牌故事、宽幅模块和小型利益点模块组织信息。",
  ],
  promptGuardrails: [
    "MAIN 必须是纯白背景、单一真实商品视图、主体完整，且不生成任何叠加文字或装饰标记。",
    "所有文字、参数、配件和使用结果必须来自用户提供的商品事实。",
  ],
  complianceReminders: [
    "A+ 不得出现价格、促销、评论、竞品声明、联系方式、无依据保证或攻击性号召。",
    "工具仅提供策划和提示检查，最终合规需按类目、站点和 Seller Central 当前规则人工确认。",
  ],
  exportRules: {
    folder: "amazon",
    fileName: (slot, extension) =>
      `amazon/${String(slot.order).padStart(2, "0")}-${slot.key}.${extension}`,
  },
});
