import { definePlatformRulePack, type PlatformSlotRule } from "./types";

const square = { width: 800, height: 800, unit: "px" } as const;
const mobileDetail = { width: 750, height: 1000, unit: "px" } as const;

const slots: PlatformSlotRule[] = [
  {
    key: "TB-HERO-01",
    label: "首图",
    group: "gallery",
    order: 1,
    required: true,
    dimensions: square,
    purpose: "用清晰主体建立第一眼识别，并传达商品品类。",
    planningHints: ["主体完整", "背景简洁", "优先使用最有代表性的商品视角"],
    complianceReminders: ["价格、促销和平台承诺需人工确认", "不得虚构商品外观或规格"],
  },
  {
    key: "TB-HERO-02",
    label: "核心卖点",
    group: "gallery",
    order: 2,
    required: true,
    dimensions: square,
    purpose: "集中说明一个最有购买价值的核心利益点。",
    planningHints: ["一图一卖点", "利益点需由商品事实支撑", "文案保持短而可扫读"],
    complianceReminders: ["避免最高级、绝对化和无依据效果承诺"],
  },
  {
    key: "TB-HERO-03",
    label: "使用场景",
    group: "gallery",
    order: 3,
    required: true,
    dimensions: square,
    purpose: "展示目标用户在真实场景中的使用方式和结果。",
    planningHints: ["场景与目标人群匹配", "商品仍是视觉焦点", "动作关系自然"],
    complianceReminders: ["不得用场景暗示产品不具备的功效"],
  },
  {
    key: "TB-HERO-04",
    label: "细节与材质",
    group: "gallery",
    order: 4,
    required: true,
    dimensions: square,
    purpose: "用结构、材质或工艺细节提供可信购买证据。",
    planningHints: ["使用近景或局部放大", "标注内容对应真实材质或结构", "优先呈现可验证差异"],
    complianceReminders: ["材质、认证和工艺描述需与资料一致"],
  },
  {
    key: "TB-HERO-05",
    label: "包装与信任",
    group: "gallery",
    order: 5,
    required: true,
    dimensions: square,
    purpose: "说明包装内容、交付形态或服务信任信息。",
    planningHints: ["展示实际包装或清单", "信息层级清楚", "只使用已确认的服务信息"],
    complianceReminders: ["赠品、服务范围和时效需人工确认"],
  },
  {
    key: "TB-DETAIL-01",
    label: "详情首屏",
    group: "detail",
    order: 6,
    required: true,
    dimensions: mobileDetail,
    purpose: "在详情页首屏建立商品价值主张和继续浏览理由。",
    planningHints: ["商品名与核心价值优先", "控制首屏信息密度", "与首图保持视觉一致"],
    complianceReminders: ["价值主张必须能由商品资料支撑"],
  },
  {
    key: "TB-DETAIL-02",
    label: "痛点与方案",
    group: "detail",
    order: 7,
    required: true,
    dimensions: mobileDetail,
    purpose: "连接用户痛点与商品提供的具体解决方式。",
    planningHints: ["描述具体使用问题", "给出对应产品机制", "避免制造焦虑"],
    complianceReminders: ["不得夸大痛点或承诺无法证明的结果"],
  },
  {
    key: "TB-DETAIL-03",
    label: "核心功能",
    group: "detail",
    order: 8,
    required: true,
    dimensions: mobileDetail,
    purpose: "按优先级解释关键功能和用户收益。",
    planningHints: ["每项功能绑定事实证据", "先结果后原理", "使用一致的视觉结构"],
    complianceReminders: ["功能与参数需和商品资料逐项核对"],
  },
  {
    key: "TB-DETAIL-04",
    label: "场景演示",
    group: "detail",
    order: 9,
    required: true,
    dimensions: mobileDetail,
    purpose: "演示商品在典型场景中的完整使用路径。",
    planningHints: ["表现使用前提和动作", "场景选择贴近目标人群", "避免遮挡关键商品结构"],
    complianceReminders: ["场景效果不得超出真实使用边界"],
  },
  {
    key: "TB-DETAIL-05",
    label: "材质与工艺",
    group: "detail",
    order: 10,
    required: true,
    dimensions: mobileDetail,
    purpose: "进一步解释材质、结构和制造工艺的价值。",
    planningHints: ["使用可验证的微距细节", "解释工艺与体验的关系", "保留真实纹理"],
    complianceReminders: ["材质、产地、专利和认证声明需有证明"],
  },
  {
    key: "TB-DETAIL-06",
    label: "规格与包装",
    group: "detail",
    order: 11,
    required: true,
    dimensions: mobileDetail,
    purpose: "集中呈现尺寸、规格、型号和包装清单。",
    planningHints: ["使用结构化参数表", "标明单位", "包装内容与实物一致"],
    complianceReminders: ["尺寸、重量、数量和型号必须人工复核"],
  },
  {
    key: "TB-DETAIL-07",
    label: "服务收尾",
    group: "detail",
    order: 12,
    required: true,
    dimensions: mobileDetail,
    purpose: "以已确认的服务和信任信息完成详情页收尾。",
    planningHints: ["只呈现可兑现服务", "明确适用条件", "避免重复前文卖点"],
    complianceReminders: ["售后、质保和物流承诺需按店铺实际政策确认"],
  },
];

export const taobaoRulePack = definePlatformRulePack({
  platformId: "taobao",
  label: "淘宝 / 天猫",
  locale: "zh-CN",
  promptLanguage: "source",
  slots,
  planningInstructions: [
    "从商品事实中提取可验证卖点，再分配到画廊图和详情页槽位。",
    "画廊图保持一图一任务，详情页形成从价值、证据到规格和服务的浏览顺序。",
  ],
  promptGuardrails: [
    "不得生成与参考资料冲突的商品结构、材质、配件或包装。",
    "涉及价格、认证、对比、功效和服务承诺时，仅使用用户明确提供的信息。",
  ],
  complianceReminders: [
    "绝对化用语、效果承诺、价格促销、资质认证和比较声明均需人工确认。",
    "平台规则会随类目和活动变化，发布前仍需在商家后台复核。",
  ],
  exportRules: {
    folder: "taobao",
    fileName: (slot, extension) =>
      `taobao/${String(slot.order).padStart(2, "0")}-${slot.key}.${extension}`,
  },
});
